### PR TITLE
Update main.f to set default gause for processes 54 and 55 to "axial"

### PR DESCRIPTION
**Pull request by andriish**
Update main.f to set default gause for processes 54 and 55 to "axial".

In this way the vector `n(4)` is initialized.

### CODE REVIEW

**Comment by LucianHL** [comment]
I don't see the issue here? wgauge is already set to 'axial' at initialisation in superchic.f. So the moving of wgauge='axial' from top to bottom seems redundant?

**Comment by andriish** [comment]
Hm. I think you are right.But let me do some more tests...

**Comment by LucianHL** [comment]
Shall I close this?

**Comment by LucianHL** [comment]
I have fixed this now in #170

**Pull request closed without merging**
