### PR TITLE
Shower the remaining cases

### PR DESCRIPTION
**Pull request by andriish**
Shower the remaining cases.

With this fix all tests should pass, however, the justification for the settings is not there and some events will be still broken.

### CODE REVIEW

**Comment by LucianHL** [comment]
Hi @andriish , thanks - these don't look appropriate though at first glance. It seems as though you are calling an internal pythia photon flux, which does not sound right, for example. And I can't see why the 'fmg2...' flags would be needed. 

So some care is needed here. How did you arrrive at these? And I am certain that the e.g. lepton case can work completely fine with the flags described in the manual/paper. i.e. without these. Indeed I think these *were* working in an earlier iteration of the code?

**Comment by andriish** [comment]
Hi @LucianHL,

For sure the setups are not good. I came to them looking at the Pythia8 photoproduction.

The bad cases were isolated in that new logic and I've tried to find a set of flags to make things work. It works now, but I don't fully understand why it works and if all the flags are needed.

Andrii

**Comment by andriish** [comment]
I mean some discussions are needed concerning the showering logic.
FOr instance it is clear that the photoproduction is showered slightly different in Pythia than it is described in the manual.

**Comment by LucianHL** [comment]
Thanks, certainly we can discuss more about the best way to shower things. At the moment my main concern though is that for e.g. lepton pair production with and without proton dissociation this should definitely work with the default flags described in the manual. So I don't see how anything new is needed in that case. And similarly for ALP production and WW.

**Comment by LucianHL** [comment]
p.s. by 'needed' I mean needed to get things to work. It might be that things can be refined of course

**Pull request closed without merging**
