### PR TITLE
raised mmax for e.g. WW production to work

### PR DESCRIPTION
**Pull request by LucianHL**

### CODE REVIEW

**Comment by LucianHL** [comment]
@andriish  - this was previously set to be < 2*M_W so the WW case was just crashing. I am now finding that processes 56-58 (dilepton production) and 68 (ALPs) are passing all tests for el,sd and dd, including for showering. Do you find that? I feel as though this was not working at some point quite recently...

WW is working in el and sd but is crashing for dd when it tries to produce unweighted events (an issue in unweight_q.f). I will look at that soon

**Comment by andriish** [comment]
Hi @LucianHL,

this LGTM and I will merge. ( Hopefully the CI will be OK, but if not -- that is a problem of apfel@MAC).

But just for a better understanding -- what is this cut and would you be so kind to add documentation on it?


Best regards,

Andrii

**Comment by andriish** [comment]
Ah, the CI fails because it is outdated.

**Comment by LucianHL** [comment]
This is just the maximum central system invariant mass that is generated, so if it is < 2*M_W then the cross section is zero. But really this should be fixed with a stop statement rather than crashing.

I'm not sure how to proceed with the CI?

**Comment by LucianHL** [comment]
sorry didn't tag you - @andriish

**Comment by andriish** [comment]
CI:  it will work in the master.

**Pull request merged**
