### PR TITLE
Generate documentation on the tests

### PR DESCRIPTION
**Pull request by andriish**
Hi @LucianHL,

please have a look.
This MR:
 - puts back the init test for AA beams. That is a pure technicality.
 - assures that all the tested processes are documented:  The list of enabled tests is saved into a tex file and (if pdflatex is available)  compiled into PDF. The location is the build_directory/test/tested.pdf An example result is attached. 
[tested.pdf](https://github.com/LucianHL/SuperChic/files/13537251/tested.pdf)

 It would be great if the documentation would contain the same table but for the allowed combinations of processes/beams.

Best regards,

Andrii

### CODE REVIEW

**Comment by LucianHL** [comment]
Hi @andriish, thank you yes indeed updating the documentation is on my to-do list. I am not sure why init should be there for AA though? It is not needed when running in AA mode, so why test for it (it takes time to do as you know)?

**Comment by andriish** [comment]
Hi @LucianHL,

init is there for e+e- as well and it is needed just as a dummy dependency for test.
If init is not needed for AA, then it makes sense just exit from init in that case, same as it is done for e+e-.

Btw, does one need init for pA?


Andrii

**Comment by andriish** [comment]
Should I add
```
      if (beam .eq. 'ion') then 
      write(*,*)'Running the init program is not required for AA beams'
      goto 999
      end if
```

**Comment by LucianHL** [comment]
Thank you, yes indeed that makes more sense, please add it for AA. I am pretty certain it is also not needed for pA so please do the same there. If everything then crashes during the tests we can always go back on that.

**Comment by LucianHL** [comment]
Shall I accept this one now or wait for a new PR?

**Comment by andriish** [comment]
Hi @LucianHL ,

ok. Done.

Best regards,

Andrii

**Pull request merged**
